#!/bin/bash

function send_notification() {
    echo "$1"
}

function assert_success() {
    "${@}"
    local status=${?}
    if [ ${status} -ne 0 ]; then
        send_notification "### Error ${status} at: ${BASH_LINENO[*]} ###"
        exit ${status}
    fi
}

app=github_releases_tgbotapi_sender
version=0.0.2

assert_success ./gradlew build
# Config for custom registry server
# server=YOUR REGISTRY ADDRESS
# assert_success docker build -t $app:"$version" .
# assert_success docker tag $app:"$version" $server/$app
# assert_success docker push $server/$app

dockerServer=docker.inmo.dev
dockerUsername=insanusmokrassar
assert_success sudo docker build -t $app:"$version" .
assert_success sudo docker tag $app:"$version" $dockerUsername/$app:$version
assert_success sudo docker tag $app:"$version" $dockerUsername/$app:latest
assert_success sudo docker push $dockerUsername/$app:$version
assert_success sudo docker push $dockerUsername/$app:latest
